//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yourInvoice.Common.ErrorHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS Project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yourInvoice.Common.ErrorHandling.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oferta no existe o no se encuentra en estado En proceso.
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que no contiene el CUFE.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que la factura no es del mismo emisor.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que la factura no es para el pagador.
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que la factura no es de tipo crédito.
        /// </summary>
        internal static string _1004 {
            get {
                return ResourceManager.GetString("1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que la factura ha sido procesada previamente.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que no cumple con el esquema de la DIAN.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que no contiene el PDF y XML.
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que contiene virus.
        /// </summary>
        internal static string _1008 {
            get {
                return ResourceManager.GetString("1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que tiene una extensión no admitida.
        /// </summary>
        internal static string _1009 {
            get {
                return ResourceManager.GetString("1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se enviaron archivos.
        /// </summary>
        internal static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que no tiene un tipo de moneda válido..
        /// </summary>
        internal static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pagador no existe.
        /// </summary>
        internal static string _1012 {
            get {
                return ResourceManager.GetString("1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe estar diligenciado, por favor verifique..
        /// </summary>
        internal static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que se encuentra vacío..
        /// </summary>
        internal static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error extrayendo el archivo: {0}.
        /// </summary>
        internal static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genera el archivo {0}..
        /// </summary>
        internal static string _1016 {
            get {
                return ResourceManager.GetString("1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se envía el archivo {0} al blob storage en la ruta {1}..
        /// </summary>
        internal static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro de conexión al service bus no está configurado.
        /// </summary>
        internal static string _1018 {
            get {
                return ResourceManager.GetString("1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro de la cola del bus para los CUFES no está configurado.
        /// </summary>
        internal static string _1019 {
            get {
                return ResourceManager.GetString("1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que supera las 5 megas.
        /// </summary>
        internal static string _1020 {
            get {
                return ResourceManager.GetString("1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que contiene el mismo CUFE que otra factura en esta misma carga de archivos..
        /// </summary>
        internal static string _1021 {
            get {
                return ResourceManager.GetString("1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. FACTURA ENDOSADA (EMISOR NO ES EL LEGÍTIMO TENEDOR).
        /// </summary>
        internal static string _1022 {
            get {
                return ResourceManager.GetString("1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. EVENTO DE PAGO ASOCIADO.
        /// </summary>
        internal static string _1023 {
            get {
                return ResourceManager.GetString("1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se envía el archivo  {0} al FTP, {1}..
        /// </summary>
        internal static string _1024 {
            get {
                return ResourceManager.GetString("1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se finaliza la búsqueda en el FTP del archivo {0} en el FTP, resultado {1}..
        /// </summary>
        internal static string _1025 {
            get {
                return ResourceManager.GetString("1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se procesa el archivo {0} cantidad de registros procesado {1} de {2}, resultado {3}.
        /// </summary>
        internal static string _1026 {
            get {
                return ResourceManager.GetString("1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna [Fecha de pago] solo permite el formato fecha dd-mm-yyyy o mm-dd-yyyy, El valor debe ser mayor a la fecha actual..
        /// </summary>
        internal static string _1027 {
            get {
                return ResourceManager.GetString("1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna [Valor neto de pago] solo permite número, El valor debe ser mayor a 0.
        /// </summary>
        internal static string _1028 {
            get {
                return ResourceManager.GetString("1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que no tiene la misma cantidad de facturas que tiene la oferta..
        /// </summary>
        internal static string _1029 {
            get {
                return ResourceManager.GetString("1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que contiene facturas no válidas en la oferta..
        /// </summary>
        internal static string _1030 {
            get {
                return ResourceManager.GetString("1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que contiene facturas con fechas menores o iguales a la de hoy..
        /// </summary>
        internal static string _1031 {
            get {
                return ResourceManager.GetString("1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que contiene valores menores o iguales que cero..
        /// </summary>
        internal static string _1032 {
            get {
                return ResourceManager.GetString("1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El catálogo no existe.
        /// </summary>
        internal static string _1033 {
            get {
                return ResourceManager.GetString("1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El beneficiario ya existe..
        /// </summary>
        internal static string _1034 {
            get {
                return ResourceManager.GetString("1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El certificado bancario es requerido.
        /// </summary>
        internal static string _1035 {
            get {
                return ResourceManager.GetString("1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento o RUT es requerido.
        /// </summary>
        internal static string _1036 {
            get {
                return ResourceManager.GetString("1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento cargado no es de formato PDF..
        /// </summary>
        internal static string _1037 {
            get {
                return ResourceManager.GetString("1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dígito de verificación es requerido.
        /// </summary>
        internal static string _1038 {
            get {
                return ResourceManager.GetString("1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden generar nuevamente los documentos, ya que ya se encuentran firmados..
        /// </summary>
        internal static string _1039 {
            get {
                return ResourceManager.GetString("1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento no existe.
        /// </summary>
        internal static string _1040 {
            get {
                return ResourceManager.GetString("1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede exceder más de la cantidad máxima parametrizada de beneficiarios..
        /// </summary>
        internal static string _1041 {
            get {
                return ResourceManager.GetString("1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún campo de valor de pago o fecha de pago puede ir vacío..
        /// </summary>
        internal static string _1042 {
            get {
                return ResourceManager.GetString("1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servidor de correo no se encuentra configurado.
        /// </summary>
        internal static string _1043 {
            get {
                return ResourceManager.GetString("1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email no es válido.
        /// </summary>
        internal static string _1044 {
            get {
                return ResourceManager.GetString("1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oferta {0} se venció porque excedió el tiempo máximo para su compra.
        /// </summary>
        internal static string _1045 {
            get {
                return ResourceManager.GetString("1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura {0} oferta {1} con estado habilitado, no se encuentra registrada..
        /// </summary>
        internal static string _1046 {
            get {
                return ResourceManager.GetString("1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura {0} oferta {1} no está registrado el pagador {2}..
        /// </summary>
        internal static string _1047 {
            get {
                return ResourceManager.GetString("1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura {0} del número de oferta {1} no está registrado el vendedor {2}..
        /// </summary>
        internal static string _1048 {
            get {
                return ResourceManager.GetString("1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oferta {0} está disponible para compra..
        /// </summary>
        internal static string _1049 {
            get {
                return ResourceManager.GetString("1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo {0} fue procesado..
        /// </summary>
        internal static string _1050 {
            get {
                return ResourceManager.GetString("1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no puede superar las 5 MB.
        /// </summary>
        internal static string _1051 {
            get {
                return ResourceManager.GetString("1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suma del tamaño de todos los archivos no debe superar los 10 MB.
        /// </summary>
        internal static string _1052 {
            get {
                return ResourceManager.GetString("1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de la factura {0} no contiene un formato válido..
        /// </summary>
        internal static string _1053 {
            get {
                return ResourceManager.GetString("1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de compra {0} debe ser mayor a la fecha final {1}.
        /// </summary>
        internal static string _1054 {
            get {
                return ResourceManager.GetString("1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de compra {0} no debe ser inferior a 1 semana..
        /// </summary>
        internal static string _1055 {
            get {
                return ResourceManager.GetString("1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el archivo {0} en el BlobStorage {1}..
        /// </summary>
        internal static string _1056 {
            get {
                return ResourceManager.GetString("1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que el campo {0} no fue encontrado en el XML..
        /// </summary>
        internal static string _1057 {
            get {
                return ResourceManager.GetString("1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al realizar la firma de los documentos con Zapsign. Por favor, intente de nuevo..
        /// </summary>
        internal static string _1058 {
            get {
                return ResourceManager.GetString("1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se generó token en el proceso de firma con zapsign..
        /// </summary>
        internal static string _1059 {
            get {
                return ResourceManager.GetString("1059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe información del resumen para el usuario, por favor verifique..
        /// </summary>
        internal static string _1060 {
            get {
                return ResourceManager.GetString("1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta con el correo electrónico ingresado ya existe..
        /// </summary>
        internal static string _1061 {
            get {
                return ResourceManager.GetString("1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta no existe..
        /// </summary>
        internal static string _1062 {
            get {
                return ResourceManager.GetString("1062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número documento {0} de la columna [Numero de documento comprador] no pertenece a un usuario comprador o el usuario no existe..
        /// </summary>
        internal static string _1063 {
            get {
                return ResourceManager.GetString("1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro {0} columna {1} está vacío, debe contener información..
        /// </summary>
        internal static string _1064 {
            get {
                return ResourceManager.GetString("1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo procesar el archivo debido que en la columna reasignación no hay registros N, R, M..
        /// </summary>
        internal static string _1065 {
            get {
                return ResourceManager.GetString("1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden procesar archivos .zip que contengan más de una factura electrónica internamente.
        /// </summary>
        internal static string _1066 {
            get {
                return ResourceManager.GetString("1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Advertencia! El valor de pago neto no puede exceder el valor de la factura más un 19%. Por favor, asegúrate de que el monto a pagar esté dentro de este límite..
        /// </summary>
        internal static string _1067 {
            get {
                return ResourceManager.GetString("1067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}030 Acuse de recibo de la factura electrónica de venta..
        /// </summary>
        internal static string _1068 {
            get {
                return ResourceManager.GetString("1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}032 Recibo del bien o prestación del servicio..
        /// </summary>
        internal static string _1069 {
            get {
                return ResourceManager.GetString("1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}033 Aceptación expresa de la facturación electrónica de venta..
        /// </summary>
        internal static string _1070 {
            get {
                return ResourceManager.GetString("1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}034 Aceptación tácita de la factura electrónica de venta..
        /// </summary>
        internal static string _1071 {
            get {
                return ResourceManager.GetString("1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}031 Reclamo de la factura electrónica de venta..
        /// </summary>
        internal static string _1072 {
            get {
                return ResourceManager.GetString("1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}036 Primera inscripción de la factura electrónica de venta como título valor en el RADIAN para negociación directa previa..
        /// </summary>
        internal static string _1073 {
            get {
                return ResourceManager.GetString("1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}037 Endoso electrónico en propiedad con responsabilidad..
        /// </summary>
        internal static string _1074 {
            get {
                return ResourceManager.GetString("1074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}037 Endoso electrónico en propiedad sin responsabilidad..
        /// </summary>
        internal static string _1075 {
            get {
                return ResourceManager.GetString("1075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}047 Endoso con efectos de cesión ordinaria..
        /// </summary>
        internal static string _1076 {
            get {
                return ResourceManager.GetString("1076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}046 Informe para el pago de la factura electrónica de venta como título valor..
        /// </summary>
        internal static string _1077 {
            get {
                return ResourceManager.GetString("1077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}045 Pago total de la factura electrónica de venta como título valor..
        /// </summary>
        internal static string _1078 {
            get {
                return ResourceManager.GetString("1078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oferta no se puede modificar debido a que su estado actual no está en progreso..
        /// </summary>
        internal static string _1079 {
            get {
                return ResourceManager.GetString("1079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oferta no se puede modificar debido a que su estado actual es comprada..
        /// </summary>
        internal static string _1082 {
            get {
                return ResourceManager.GetString("1082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema no pudo cargar información para el usuario actual, por favor verifique..
        /// </summary>
        internal static string _1083 {
            get {
                return ResourceManager.GetString("1083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} está registrada para el usuario actual..
        /// </summary>
        internal static string _1084 {
            get {
                return ResourceManager.GetString("1084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El total supera el límite de {0} Ajuste los valores..
        /// </summary>
        internal static string _1085 {
            get {
                return ResourceManager.GetString("1085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede registrar, porque no es de tipo jurídico..
        /// </summary>
        internal static string _1086 {
            get {
                return ResourceManager.GetString("1086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los documentos ya se encuentran firmados, no es posible firmarlos de nuevo..
        /// </summary>
        internal static string _1087 {
            get {
                return ResourceManager.GetString("1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los documentos ya se encuentran firmados y están pendientes de aprobación..
        /// </summary>
        internal static string _1088 {
            get {
                return ResourceManager.GetString("1088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden generar los archivos porque uno o más formularios en el proceso de vinculación no se encuentran completos, verifique nuevamente..
        /// </summary>
        internal static string _1089 {
            get {
                return ResourceManager.GetString("1089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error generando el archivo: {0}.
        /// </summary>
        internal static string _1090 {
            get {
                return ResourceManager.GetString("1090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo ha sido rechazado, ya que la información dentro del xml es invalida..
        /// </summary>
        internal static string _1091 {
            get {
                return ResourceManager.GetString("1091", resourceCulture);
            }
        }
    }
}
